### ISSUE TITLE
ช่วยแนะนำการใช้งานได้มั้ยครับ

### ISSUE THREAD

**Issue by kittipongkp** [dtinth/reactbkk-tweets-backend#2]
ช่วยแนะนำการใช้งานได้มั้ยครับ

**Comment by dtinth** [comment]
Repo นี้เป็น script ที่เอาไว้ดึง tweets จาก Twitter โยนขึ้น Firebase ครับ

โค้ดอยู่ที่ https://github.com/reactbkk/tweetboard-backend/blob/master/worker.js

1. กำหนด Environment variables ให้เรียบร้อยก่อนรัน โดย Environment variables ที่ใช้ ให้ดูในโค้ดครับ ที่ขึ้นต้นด้วย process.env เช่น `$ export FIREBASE_PRIVATE_KEY=/path/to/service-account.json`

2. แก้ `databaseURL` ในโค้ด ให้ชี้ไปที่ Firebase ที่ต้องการ

3. แก้โค้ดตรง `track:` โดยใส่ keyword ที่ต้องการติดตามเข้าไปแทน

4. รันไฟล์ worker.js ได้เลยครับ

หากรันได้อย่างถูกต้อง เวลามีข้อความใหม่ ข้อมูลของ status นั้น จะขึ้นไปโผล่ใน Firebase Realtime Database โดยสามารถเช็คได้ใน Firebase Console ครับ

**Comment by kittipongkp** [comment]
พอจะเข้าใจเเนวทางเเล้วครับ  ขอบคุณมากครับ
